SHARKNA/ViewModels/BoardRequestsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using SHARKNA.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SHARKNA.ViewModels
{
    public class BoardRequestsViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("اسم المستخدم")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [DisplayName("اسم النادي")]
        public Guid BoardId { get; set; }
        public string BoardName { get; set; }

        [DisplayName("الوصف")]
        public string BoardDescription { get; set; }

        
        [DisplayName("حالة الطلب")]
        public Guid RequestStatusId { get; set; }

        public string RequestStatusName { get; set; }

        public ICollection<tblBoards> BoardsOfList { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("البريد الإلكتروني")]
        public string Email { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(13)]
        [DisplayName("رقم الجوال")]
        public string MobileNumber { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("الاسم")]
        public string FullNameAr { get; set; }

        //[Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("الاسم بالانجليزي")]
        public string FullNameEn { get; set; }

        [StringLength(1000)]
        [DisplayName(" سبب الرفض")]
        public string? RejectionReasons { get; set; }

    }
}

SHARKNA/Areas/Admin/Controllers/BoardRequestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SHARKNA.Domain;
using SHARKNA.ViewModels;
using System.Security;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SHARKNA.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Super Admin,Editor")]

    public class BoardRequestsController : Controller
    {
        private readonly BoardRequestsDomain _boardRequestsDomain;
        private readonly BoardDomain _BoardDomain;
        private readonly RequestStatusDomain _RequestStatusDomain;
        private readonly BoardMembersDomain _BoardMembersDomain;
        private readonly UserDomain _UserDomain;

        public BoardRequestsController(BoardRequestsDomain boardRequestsDomain, BoardDomain BoardDomain, RequestStatusDomain requestStatusDomain, BoardMembersDomain boardMembersDomain, UserDomain userDomain)
        {
            _boardRequestsDomain = boardRequestsDomain;
            _BoardDomain = BoardDomain;
            _RequestStatusDomain = requestStatusDomain;
            _BoardMembersDomain = boardMembersDomain;
            _UserDomain = userDomain;
        }

        
        public async Task<IActionResult> UserDetails()
        {
            var userBoardRequests =  _BoardDomain.GetTblBoards();
            return View(userBoardRequests);
        }


        public async Task<IActionResult> Admin()
        {
            var BoardReq = await _boardRequestsDomain.GetTblBoardRequestsAsync();
            return View(BoardReq);
        }

        public async Task<IActionResult> Archive()
        {
            var BoardReq = await _boardRequestsDomain.GetTblBoardRequestsAsync();
            return View(BoardReq);
        }

        public async Task<IActionResult> Create(Guid boardId)
        {
            var username = User.FindFirst(ClaimTypes.Name)?.Value;
            var user = await _UserDomain.GetUserFERAsync(username);
            var board = await _BoardDomain.GetTblBoardByIdAsync(boardId);

            var model = new BoardRequestsViewModel
            {
                
                BoardId = boardId,
                BoardName = board.NameAr,
                BoardDescription = board.DescriptionAr,
            };

            return View(model);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var request = await _boardRequestsDomain.GetBoardRequestByIdAsync(id);
            return View(request);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BoardRequestsViewModel BoardReq, string UserName)
        {
            try
            {
                //var user = await _boardRequestsDomain.GetAllUsers(BoardReq.UserName); 
                var user = await _boardRequestsDomain.GetAllUsers(); 
                if (user == null)
                {
                    ViewData["Falied"] = "لم يتم العثور على المستخدم";
                    return View(BoardReq);
                }

                if (ModelState.IsValid)
                {
                    string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims
                    BoardReq.Id = Guid.NewGuid();
                    await _boardRequestsDomain.AddBoardReqAdminAsync(BoardReq);
                    ViewData["Successful"] = "تم التسجيل بنجاح ";
                    int check = await _boardRequestsDomain.AddBoardReqAsync(BoardReq, UserName , username);
                    if (check == 1)
                    {
                        ViewData["Successful"] = "تم التسجيل بنجاح";
                    }
                    else
                    {
                        ViewData["Falied"] = "حدث خطأ";
                    }
                    return View(BoardReq);
                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ";
            }

            return View(BoardReq);
        }

        public async Task<UserViewModel> GetUserInfo(string id)
        {
            return await _UserDomain.GetTblUserByUserName(id);
        }


        [HttpGet]
        public async Task<IActionResult> Accept(Guid id)
        {
            try
            {
                string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims
                await _boardRequestsDomain.AcceptAsync(id , username);
                ViewData["Successful"] = "تم قبول الطلب بنجاح.";
            }
            catch (Exception)
            {
                ViewData["Falied"] = "حدث خطأ أثناء محاولة إلغاء الطلب.";
            }

            return RedirectToAction(nameof(Admin));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Reject(Guid id, string rejectionReason)
        {
            try
            {
                string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims
                await _boardRequestsDomain.RejectAsync(id, rejectionReason, username);
                ViewData["Successful"] = "تم رفض الطلب بنجاح.";
            }
            catch (Exception)
            {
                ViewData["Falied"] = "حدث خطأ أثناء محاولة رفض الطلب.";
            }

            return RedirectToAction(nameof(Admin));
        }
    }
}

SHARKNA/Controllers/BoardRequestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SHARKNA.Domain;
using SHARKNA.Models;
using SHARKNA.ViewModels;
using System.Diagnostics;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SHARKNA.Controllers
{
    public class BoardRequestsController : Controller
    {
        private readonly BoardRequestsDomain _boardRequestsDomain;
        private readonly BoardDomain _BoardDomain;
        private readonly RequestStatusDomain _RequestStatusDomain;
        private readonly BoardMembersDomain _BoardMembersDomain;
        private readonly UserDomain _UserDomain;

        public BoardRequestsController(BoardRequestsDomain boardRequestsDomain, BoardDomain BoardDomain, RequestStatusDomain requestStatusDomain, BoardMembersDomain boardMembersDomain, UserDomain userDomain)
        {
            _boardRequestsDomain = boardRequestsDomain;
            _BoardDomain = BoardDomain;
            _RequestStatusDomain = requestStatusDomain;
            _BoardMembersDomain = boardMembersDomain;
            _UserDomain = userDomain;
        }

        [Authorize(Roles = "NoRole,User,Admin,SuperAdmin,Editor")]
        public async Task<IActionResult> Index(string Successful = "", string Falied = "")
        {
            if (!string.IsNullOrEmpty(Successful))
                ViewData["Successful"] = Successful;
            else if (!string.IsNullOrEmpty(Falied))
                ViewData["Falied"] = Falied;

            var username = User.FindFirst(ClaimTypes.Name)?.Value;
            var userBoardRequests = await _boardRequestsDomain.GetTblBoardRequestsByUserAsync(username);

            return View(userBoardRequests);
        }

        [Authorize(Roles = "NoRole,User,Admin,Super Admin,Editor")]
        public async Task<IActionResult> UserDetails()
        {
            var username = User.FindFirst(ClaimTypes.GivenName)?.Value;
            var userGender = User.FindFirst(ClaimTypes.Gender)?.Value ?? "NotSpecified";
            var userBoardRequests = await _BoardDomain.GetTblBoardsAsync(userGender);
            return View(userBoardRequests);
        }

        [Authorize(Roles = "NoRole,User,Admin,SuperAdmin,Editor")]
        public async Task<IActionResult> Archive()
        {
            var username = User.FindFirst(ClaimTypes.Name)?.Value;
            var userBoardRequests = await _boardRequestsDomain.GetTblBoardRequestsByUserAsync(username);

            return View(userBoardRequests);
        }

        [Authorize(Roles = "NoRole,User,Admin,Super Admin,Editor")]
        public async Task<IActionResult> Details(Guid id)
        {
            var request = await _boardRequestsDomain.GetBoardRequestByIdAsync(id);
            return View(request);
        }

        [Authorize(Roles = "NoRole,User,Admin,Super Admin,Editor")]
        public async Task<IActionResult> Create(Guid boardId)
        {
            var username = User.FindFirst(ClaimTypes.Name)?.Value;
            var user = await _UserDomain.GetUserFERAsync(username);
            var board = await _BoardDomain.GetTblBoardByIdAsync(boardId);

            var model = new BoardRequestsViewModel
            {
                UserName = username,
                Email = user.Email,
                MobileNumber = user.MobileNumber,
                FullNameAr = user.FullNameAr,
                BoardId = boardId,
                BoardName = board.NameAr,
                BoardDescription = board.DescriptionAr,
                FullNameEn = user.FullNameEn
            };

            return View(model);
        }


        public async Task<IActionResult> MyBoards()
        {
            string username = User.FindFirst(ClaimTypes.Name)?.Value;

           
            var userBoards = await _boardRequestsDomain.GetTblBoardsByUserAsync(username);

            var boardViewModels = userBoards.Select(board => new BoardViewModel
            {
                Id = board.Id,
                NameAr = board.NameAr, 
                DescriptionAr = board.DescriptionAr
                                                
            }).ToList();

            return View(boardViewModels);

            //return View(userBoards);
        }



        [Authorize(Roles = "NoRole,User,Admin,SuperAdmin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BoardRequestsViewModel BoardReq, string UserName)
        {
            try
            {
                var username = User.FindFirst(ClaimTypes.Name)?.Value;
                var user = await _UserDomain.GetUserFERAsync(username);

                bool canMakeNewRequest = await _boardRequestsDomain.CanUserMakeNewRequestAsync(user.Email, BoardReq.BoardId);

                if (!canMakeNewRequest)
                {
                    ViewData["Falied"] = "لا يمكنك تقديم طلب جديد لهذا النادي، لديك طلب سابق.";
                    return View(BoardReq);
                }
                if (ModelState.IsValid)
                {
                    BoardReq.Id = Guid.NewGuid();
                    BoardReq.UserName = username;
                    BoardReq.Email = user.Email;
                    BoardReq.MobileNumber = user.MobileNumber;
                    BoardReq.FullNameAr = user.FullNameAr;
                    BoardReq.FullNameEn = user.FullNameEn;

                    int check = await _boardRequestsDomain.AddBoardReqAsync(BoardReq, UserName ,username);
                    if (check == 1)
                    {
                        ViewData["Successful"] = "تم تسجيل طلبك بنجاح";
                    }
                    else
                    {
                        ViewData["Falied"] = "حدث خطأ";
                    }
                    return View(BoardReq);
                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ";
            }

            return View(BoardReq);
        }



        [Authorize(Roles = "NoRole,User,Admin,SuperAdmin,Editor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelRequest(Guid id)
        {
            try
            {
                string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims
                await _boardRequestsDomain.CancelRequestAsync(id ,username);
                ViewData["Successful"] = "تم إلغاء الطلب بنجاح.";
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ أثناء محاولة إلغاء الطلب.";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

SHARKNA/Areas/Admin/Views/BoardRequests/Admin.cshtml
 @model IEnumerable<BoardRequestsViewModel>

<!DOCTYPE html>
<html lang="en" dir="rtl" data-theme="light">
<body>
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-3">
                    <h5 class="m-0">إدارة طلبات الاندية</h5>
                    <div class="d-flex gap-2">
                        <div class="form-group">
                            <input type="text" class="form-control table__quick_search" placeholder="البحث السريع ...">
                        </div>
                        <div>
                           @*  <a asp-action="UserDetails" class="btn btn-primary">التسجيل في نادي </a> *@
                        </div>
                    </div>
                </div>
                <div class="block-body">
                    <table class="table table-hover js-dataTable">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.FullNameAr)</th>
                                <th>@Html.DisplayNameFor(m => m.BoardId)</th>
                                <th>@Html.DisplayNameFor(m => m.RequestStatusId)</th>
                                <th>الإجراءات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var request in Model.Where(r => r.RequestStatusId == Guid.Parse("93d729fa-e7fa-4ea6-bb16-038454f8c5c2")))
                            {
                                <tr>
                                    <td>@request.FullNameAr</td>
                                    <td>@request.BoardName</td>
                                    <td>
                                        <span style="@(request.RequestStatusName == "تحت الدراسة" ? "background-color: gold; padding: 2px 6px; border: 1px solid goldenrod; display: inline-block; border-radius: 5px;" : "")">
                                            @request.RequestStatusName 
                                        </span>
                                    </td>
                                    <td>
                                        <form asp-action="Details">
                                            <input type="hidden" name="id" value="@request.Id" />
                                            <button type="submit" class="btn" style="background-color: rgb(15, 113, 121); color: white;">تفاصيل الطلب</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

SHARKNA/Areas/Admin/Views/BoardRequests/Archive.cshtml
 @model IEnumerable<BoardRequestsViewModel>

<!DOCTYPE html>
<html lang="en" dir="rtl" data-theme="light">
<body>
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-3">
                    <h5 class="m-0">إدارة طلبات الاندية</h5>
                    <div class="d-flex gap-2">
                        <div class="form-group">
                            <input type="text" class="form-control table__quick_search" placeholder="البحث السريع ...">
                        </div>
                        <div>
                           @*  <a asp-action="UserDetails" class="btn btn-primary">التسجيل في نادي </a> *@
                        </div>
                    </div>
                </div>
                <div class="block-body">
                    <table class="table table-hover js-dataTable">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.FullNameAr)</th>
                                <th>@Html.DisplayNameFor(m => m.BoardId)</th>
                                <th>@Html.DisplayNameFor(m => m.RequestStatusId)</th>
                              
                                <th>الإجراءات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var request in Model.Where(r => r.RequestStatusId != Guid.Parse("93d729fa-e7fa-4ea6-bb16-038454f8c5c2")))
                            {
                                <tr>
                                    <td>@request.FullNameAr</td>
                                    <td>@request.BoardName</td>
                                    <td>
                                        <span style="@(request.RequestStatusName == "مقبول" ? "background-color: lightgreen; padding: 2px 6px; border: 1px solid green; display: inline-block; border-radius: 5px;" :
                                                      request.RequestStatusName == "مرفوض" ? "background-color: lightcoral; padding: 2px 6px; border: 1px solid red; display: inline-block; border-radius: 5px;" :
                                                      request.RequestStatusName == "تم الالغاء" ? "background-color: gray; padding: 2px 6px; border: 1px solid black; display: inline-block; border-radius: 5px;" : "")">
                                            @request.RequestStatusName 
                                        </span>
                                    </td>
                                    <td>
                                        <form asp-action="Details">
                                            <input type="hidden" name="id" value="@request.Id" />
                                            <button type="submit" class="btn" style="background-color: rgb(15, 113, 121); color: white;">تفاصيل الطلب</button>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

SHARKNA/Areas/Admin/Views/BoardRequests/Create.cshtml
@model SHARKNA.ViewModels.BoardRequestsViewModel

@{
    string boardIdString = Context.Request.Query["boardId"];

    Guid boardId = Guid.Empty;
}
<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                                                                                            var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("UserDetails", "BoardRequests")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                                                                                            var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                                                                                            var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>

<section class="page_wrap">
    <div class="page_content">

        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h5 class="m-0">@Model.BoardName</h5>
            </div>
            <div class="block-body py-5">
                        <label id="lblError" d style="color:red; display:none">هذا المستخدم غير موجود في قاعدة البيانات</label>
                        <form asp-action="Create" method="post">
                               
                        <div class="row">

                            <div class="col-md-6">
                                <div class="mb-4">
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.UserName)</label>
                                        <input asp-for="UserName" type="text" class="form-control" id="UserName">
                                    <span asp-validation-for="UserName" class="text-danger"></span>

                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-4">
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.FullNameAr) </label>
                                    <input asp-for="FullNameAr" type="text" class="form-control" id="FullNameAr">
                                    <span asp-validation-for="FullNameAr" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-4">
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.Email)</label>
                                    <input asp-for="Email" type="email" class="form-control text-start" id="Email">
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-4">
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.MobileNumber)</label>
                                    <input asp-for="MobileNumber" type="tel" placeholder=" " class="form-control" id="MobileNumber" maxlength="13">
                                    <span asp-validation-for="MobileNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <div class="col-md-6">
                                <div class="mb-4">
                                    <input asp-for="BoardId" type="hidden" />
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.BoardId)</label>
                                    <input asp-for="BoardName" type="text" class="form-control" readonly />
                                    <span asp-validation-for="BoardName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="mb-4">
                                    <label for="" class="mb-1">@Html.DisplayNameFor(m => m.BoardDescription)</label>
                                    <textarea asp-for="BoardDescription" type="text" class="form-control" readonly></textarea>
                                    <span asp-validation-for="BoardDescription" class="text-danger"></span>
                                </div>
                            </div>

                        </div>
                        <div class=" d-flex justify-content-center">
                            <a href="@Url.Action("UserDetails", "BoardRequests")" class="btn btn-secondary col-3 mx-2">العودة</a>
                            <button type="submit" value="Create" class="btn btn-primary col-3 mx-2" title="save">تسجيل</button>
                        </div>
                    </form>


                </table>
            </div>
        </div>



    </div>
</section>

<script>

        $("#UserName").on("change", function () {
            showValue($(this).val());
        });

    function showValue(val) {
        $.getJSON('@Url.Action("GetUserInfo", "Permission")/' + val, function (result) {
            console.log(result);
            $("#FullNameAr").val("");
            $("#FullNameEn").val("");
            if (result != null) {
                $("#FullNameAr").val(result.fullNameAr);
                $("#FullNameEn").val(result.fullNameEn);
                $("#lblError").toggle(false);
            }
            else {
                $("#FullNameAr").val("");
                $("#FullNameEn").val("");
                $("#lblError").toggle(true);
            }
        });
    }
</script>

SHARKNA/Areas/Admin/Views/BoardRequests/UserDetails.cshtml
 @model IEnumerable<BoardViewModel>

<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                                                                                var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "BoardRequests")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                                                                                var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                                                                                var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>


<section class="page_wrap">
    <div class="page_content">

        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h4 class="m-0">اللجان و الأندية</h4>
            </div>
            <div class="block-body py-5">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="row">
                            @foreach (var Item in Model)
                            {
                                <div class="col-md-4 mb-4">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h5 class="card-title">@Item.NameAr</h5>
                                        </div>
                                        <div class="card-footer">

                                            <form asp-action="Create" method="get">
                                                <input type="hidden" name="BoardId" value="@Item.Id" />
                                                <button type="submit" class="btn btn-primary w-100">التفاصيل </button>
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            }
                        </div>


                    </div>
                </div>
            </div>
        </div>



    </div>
</section>