SHARKNA/ViewModels/BoardRolesViewModel.cs
using SHARKNA.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;




namespace SHARKNA.ViewModels
{
    public class BoardRolesViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("الاسم العربي")]
        
        public string NameAr { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("الاسم بالانجليزي")]
        public string NameEn { get; set; }

        public bool IsDeleted { get; set; }

        public bool IsActive { get; set; }





    }
}

SHARKNA/Areas/Admin/Controllers/BoardRolesController.cs
using Microsoft.AspNetCore.Mvc;
using SHARKNA.Models;
using SHARKNA.Domain;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using SHARKNA.ViewModels;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

namespace SHARKNA.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BoardRolesController : Controller
    {
        private readonly BoardRolesDomain _BoardRolesDomain;

        public BoardRolesController(BoardRolesDomain boardRoles)
        {
            _BoardRolesDomain = boardRoles;
        }

        public IActionResult Index(string Successful = "", string Falied = "")
        {
            if (Successful != "")
                ViewData["Successful"] = Successful;
            else if (Falied != "")
                ViewData["Falied"] = Falied;

            var boardRoles = _BoardRolesDomain.GettbBoardRoles();
            return View(boardRoles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BoardRolesViewModel boardRoles)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    boardRoles.Id = Guid.NewGuid();

                    int check = _BoardRolesDomain.AddBoardRoles(boardRoles);
                    // return RedirectToAction(nameof(Index));
                    if (check == 1)
                        ViewData["Successful"] = "تم إضافة  بنجاح";
                    else
                        ViewData["Falied"] = "حدث خطأ بالإضافة";
                    return View(boardRoles);

                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ أثناء إضافة لجنة";
            }

            return View(boardRoles);
        }


        public IActionResult Edit(Guid id)
        {

            var boardRoles = _BoardRolesDomain.GetTblBoardRolesById(id);
            if (boardRoles == null)
            {
                return NotFound();
            }
            return View(boardRoles);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BoardRolesViewModel boardRoles)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    int check = _BoardRolesDomain.UpdateBoardRoles(boardRoles);
                    if (check == 1)
                        ViewData["Successful"] = "تم التعديل بنجاح";
                    else
                        ViewData["Falied"] = "خطأ بالتعديل";
                    return View(boardRoles);

                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ في أثناء التعديل";
            }
            return View(boardRoles);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Guid id)
        {
            string Successful = "";
            string Falied = "";
            try
            {


                int check = _BoardRolesDomain.DeleteBoaRoles(id);
                if (check == 1)
                {
                    Successful = "تم حذف  بنجاح";
                }

                else
                {
                    Falied = "حدث خطأ";


                }


            }
            catch (Exception ex)
            {
                Falied = "حدث خطأ";

            }
            //_boardDomain.DeleteBoard(id);
            return RedirectToAction(nameof(Index), new { Successful, Falied });


        }


    }
}

SHARKNA/Areas/Admin/Views/BoardRoles/Create.cshtml
@model SHARKNA.ViewModels.BoardRolesViewModel

@{
    ViewData["Title"] = "Create boardRoles";
}
<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "BoardRoles")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>


<!DOCTYPE html>
<html lang="ar" dir="rtl">

<body>
    
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-4">
                    <h5 class="m-0">إضافة أدوار مجلس الإدارة</h5>
                </div>
                <div class="block-body py-5">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <form asp-action="Create" method="post">
                                <div class="row">
                                    <!-- START ITEM -->
                                    <div class="col-md-6">
                                        <div class="mb-4">
                                            <label for="NameAr" class="mb-1">الاسم بالعربي</label>
                                            <input asp-for="NameAr" type="text" placeholder="الاسم بالعربي" class="form-control">
                                            <span asp-validation-for="NameAr" class="text-danger"></span>
                                        </div>
                                    </div><!-- END ITEM -->

                                    <div class="col-md-6">
                                        <div class="mb-4">
                                            <label for="NameEn" class="mb-1">الاسم بالانجليزي</label>
                                            <input asp-for="NameEn" type="hidden" placeholder="الاسم بالانجليزي" class="form-control">
                                            <span asp-validation-for="NameEn" class="text-danger"></span>
                                        </div>
                                    </div><!-- END ITEM -->
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary px-5" title="save">حفظ</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Page Wrap -->
    <div>
        <a asp-action="Index">العودة إلى القائمة</a>
    </div>

</body>
</html>

SHARKNA/Areas/Admin/Views/BoardRoles/Edit.cshtml
@model SHARKNA.ViewModels.BoardRolesViewModel

@{
    ViewData["Title"] = "Edit Event";
}

<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "BoardRoles")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
</head>
<body>
    <!-- Start Page Wrap -->
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-4">
                    <h5 class="m-0">تعديل أدوار </h5>
                </div>
                <div class="block-body py-5">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <form asp-action="Edit" method="post">
                                <input type="hidden" asp-for="Id" />
                                <div class="row">
                                    <!-- START ITEM -->
                                    <div class="col-md-6">
                                        <div class="mb-4">
                                            <label for="NameAr" class="mb-1">الاسم بالعربي</label>
                                            <input asp-for="NameAr" type="text" placeholder="الاسم" class="form-control">
                                            <span asp-validation-for="NameAr" class="text-danger"></span>
                                        </div>
                                    </div><!-- END ITEM -->
                                    <!-- START ITEM -->
                                    <div class="col-md-6">
                                        <div class="mb-4">
                                            <label for="NameEn" class="mb-1">NameEn</label>
                                            <input asp-for="NameEn" type="text" placeholder="Name" class="form-control">
                                            <span asp-validation-for="NameEn" class="text-danger"></span>
                                        </div>
                                    </div><!-- END ITEM -->
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary px-5" title="save">حفظ</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Page Wrap -->
    <div>
        <a asp-action="Index">العودة إلى القائمة</a>
    </div>
</body>
</html>

SHARKNA/Areas/Admin/Views/BoardRoles/Index.cshtml
@model IEnumerable<BoardRolesViewModel>

@{
    ViewData["Title"] = "BoardRoles List";
}

<script>
    @{
        if (ViewData["Successful"] != null)
        {
            <text>
                            var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "BoardRoles")';
                    }
                );
            </text>
        }
        else if (ViewData["Failed"] != null && ViewData["NoRedirect"] == null)
        {
            <text>
                            var result = '@Html.Raw(ViewData["Failed"])';
            Swal.fire(result, '', 'error');
            </text>
        }
        else if (ViewData["Failed"] != null && ViewData["NoRedirect"] != null)
        {
            <text>
                            var result = '@Html.Raw(ViewData["Failed"])';
            Swal.fire(result, '', 'error');
            </text>
        }
    }
</script>

<!DOCTYPE html>
<html lang="ar" dir="rtl" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
</head>
<body>
    <!-- Start Page Wrap -->
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-3">
                    <h5 class="m-0">إدارة أدوار مجلس الإدارة</h5>
                    <div class="d-flex gap-2">
                        <div class="form-group">
                            <input type="text" class="form-control table__quick_search" placeholder="البحث السريع ...">
                        </div>
                        <div>
                            <a asp-action="Create" class="btn btn-primary">إضافة أدوار مجلس الإدارة</a>
                        </div>
                    </div>
                </div>
                <div class="block-body">
                    <table class="table table-hover js-dataTable">
                        <thead>
                            <tr>
@*                               <th>@Html.DisplayNameFor(model => model.First().NameEn)</th>
 *@                              <th>@Html.DisplayNameFor(model => model.NameEn)</th>
                              <th>@Html.DisplayNameFor(model => model.NameAr)</th>
@*                               <th>@Html.DisplayNameFor(model => model.First().NameAr)</th>
 *@                              <th>الإجراءات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var boardRoles in Model)
                            {
                                <tr>
                                    <td>@boardRoles.NameEn</td>
                                    <td>@boardRoles.NameAr</td>
                                    <td class="action_td text-end">
                                        <div class="d-flex gap-2">
                                            <a asp-action="Edit" asp-route-id="@boardRoles.Id" class="btn btn-sm btn-success">تعديل</a>
                                            <form asp-action="Delete" asp-route-id="@boardRoles.Id" method="post" style="display:inline;">
                                               <button type="submit" class="btn btn-danger" onclick="return functionConfirm(this)">حذف</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section><!-- End Page Wrap -->
    <!-- Start Footer -->
    <footer class="d-flex justify-content-center align-items-center">
        <p class="m-0 d-flex justify-content-center">
            جميع الحقوق محفوظة لجامعة الملك فيصل 2024 © | تصميم وتطوير عمادة التعلم الإلكتروني وتقنية المعلومات
        </p>
    </footer><!-- End Footer -->
</body>
</html>