SHARKNA/ViewModels/BoardViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Reflection;

namespace SHARKNA.ViewModels
{
    public class BoardViewModel
    {

        public Guid Id { get; set; }
        //first

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("اسم اللجنة ")]
        public string NameAr { get; set; }

        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(100)]
        [DisplayName("اسم اللجنة بالإنجليزي")]
        public string NameEn { get; set; }


        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(5000)]
        [DisplayName("الوصف بالعربي")]
        public string DescriptionAr { get; set; }


        [Required(ErrorMessage = "هذا الحقل اجباري")]
        [StringLength(5000)]
        [DisplayName("الوصف بالإنجليزي")]
        public string DescriptionEn { get; set; }

        [DisplayName("الجنس")]
        public bool? Gender { get; set; }


        [Required(ErrorMessage = "هذا الحقل اجباري")]
        
        [DisplayName("محذوف؟")]
        public bool IsDeleted { get; set; }


        [Required(ErrorMessage = "هذا الحقل اجباري")]
        
        [DisplayName("نشط؟")]
        public bool IsActive { get; set; }



    }
}

SHARKNA/Areas/Admin/Controllers/BoardsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SHARKNA.Domain;
using SHARKNA.Models;
using SHARKNA.ViewModels;
using System.Diagnostics;
using System.Security.Claims;

namespace SHARKNA.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BoardsController : Controller
    {
        private readonly BoardDomain _boardDomain;
        private readonly UserDomain _UserDomain;


        public BoardsController(BoardDomain boardDomain, UserDomain userDomain)
        {
            _boardDomain = boardDomain;
            _UserDomain = userDomain;
        }

        [Authorize(Roles = "Admin,Super Admin,Editor")]
        public IActionResult Index(string Successful = "", string Falied = "")
        {

            if (Successful != "")
                ViewData["Successful"] = Successful;
            else if (Falied != "")
                ViewData["Falied"] = Falied;



            var boards = _boardDomain.GetTblBoards();
            return View(boards);
        }
        [Authorize(Roles = "Admin,Super Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin,Super Admin,Editor")]
        public async Task<IActionResult> Update(Guid id)
        {
            var board = await _boardDomain.GetTblBoardByIdAsync(id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }
        [Authorize(Roles = "Admin,Super Admin,Editor")]
        public async Task<IActionResult> Details(Guid id)
        {
            var board = await _boardDomain.GetTblBoardByIdAsync(id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BoardViewModel board)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    //if (await _boardDomain.IsBoardNameDuplicateAsync(board.NameEn))
                    //{
                    //    ViewData["Falied"] = "اسم اللجنة مستخدم بالفعل";
                    //    return View(board);
                    //}

                    board.Id = Guid.NewGuid();

                    string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims
                    //string fullNameAr = await _boardDomain.GetFullNameArByUsernameAsync(username);


                    int check = await _boardDomain.AddBoardAsync(board, username); // Pass the username and board to the domain method
                    if (check == 1)
                        ViewData["Successful"] = "تم إضافة اللجنة بنجاح";
                    else
                        ViewData["Falied"] = "حدث خطأ بالإضافة";
                    return View(board);

                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ أثناء إضافة لجنة";
            }

            return View(board);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Update(BoardViewModel board)
        {
            try
            {
                if (ModelState.IsValid)
                {



                    var Eboard = await _boardDomain.GetTblBoardByIdAsync(board.Id);//ياخذ بيانات اللجنة الحالموجودة حاليا من الداتابيس باستخدام ID قبل اي تعديل  


                    string username = User.FindFirst(ClaimTypes.Name)?.Value; // Get the username from claims

                    int check = await _boardDomain.UpdateBoardAsync(board, username);
                    if (check == 1)
                        ViewData["Successful"] = "تم التعديل بنجاح";
                    else
                        ViewData["Falied"] = "خطأ بالتعديل";
                    return View(board);

                }
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ أثناء التعديل";
            }
            return View(board);
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id, Guid boardId)
        {
            try
            {
                string username = User.FindFirst(ClaimTypes.Name)?.Value;

                await _boardDomain.DeleteBoardAsync(id, username);
                ViewData["Successful"] = "تم حذف اللجنة بنجاح";
            }
            catch (Exception ex)
            {
                ViewData["Falied"] = "حدث خطأ أثناء محاولة الحذف .";
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

SHARKNA/Areas/Admin/Views/Boards/Create.cshtml
@model SHARKNA.ViewModels.BoardViewModel
@{
    ViewData["Title"] = "Create Board";
}
<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "Boards")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                        var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>
@* <h2>اضافة لجنة</h2>
 *@
<section class="page_wrap">
    <div class="page_content">

        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h5 class="m-0">إضافة لجنة</h5>
            </div>
            <div class="block-body py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form asp-action="Create" method="post">
                            <div class="row">
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">اسم اللجنة بالعربي</label>
                                        <input asp-for="NameAr" type="text" placeholder="اسم اللجنة " class="form-control">
                                        <span asp-validation-for="NameAr" class="text-danger"></span>

                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1"> اسم اللجنة بالانجليزي</label>
                                        <input asp-for="NameEn" type="text" placeholder="اسم اللجنة بالإنجليزي"
                                               class="form-control text-start">
                                        <span asp-validation-for="NameEn" class="text-danger"></span>

                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">الوصف بالعربي</label>
                                        <textarea asp-for="DescriptionAr" type="text" class="form-control text-start"></textarea>
                                        <span asp-validation-for="DescriptionAr" class="text-danger"></span>
                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1"> الوصف بالإنجليزي </label>
                                        <textarea asp-for="DescriptionEn" type="text" class="form-control"> </textarea>
                                        <span asp-validation-for="DescriptionEn" class="text-danger"></span>

                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">الجنس</label>
                                        <div class="form-check">
                                            <input type="radio" asp-for="Gender" class="form-check-input" id="Male" name="Gender" value="true" />
                                            <label class="form-check-label" for="Male"> طلاب </label>
                                        </div>
                                        <div class="form-check">
                                            <input type="radio" asp-for="Gender" class="form-check-input" id="Female" name="Gender" value="false" />
                                            <label class="form-check-label" for="Female"> طالبات</label>
                                        </div>
                                        <div class="form-check">
                                            <input type="radio" asp-for="Gender" class="form-check-input" id="Both" name="Gender" value="" checked="checked" />
                                            <label class="form-check-label" for="Both"> طلاب وطالبات </label>
                                        </div>
                                        <span asp-validation-for="Gender" class="text-danger"></span>
                                    </div>
                                </div>
                                <!-- END ITEM -->



                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="submit" value="Create" class="btn btn-primary px-5" title="save">حفظ</button>
                            </div>

                        </form>


                    </div>
                </div>
            </div>
        </div>



    </div>
</section><!-- End Page Wrap -->

SHARKNA/Areas/Admin/Views/Boards/Details.cshtml
@model SHARKNA.ViewModels.BoardViewModel

@{
    ViewData["Title"] = "تفاصيل اللجنة";
}

<section class="page_wrap">
    <div class="page_content">
        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h5 class="m-0">تفاصيل لجنة @Model.NameAr</h5>
            </div>
            <div class="block-body py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8">


                        <form>
                            <div class="row">
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="NameAr" class="mb-1">اسم اللجنة بالعربي</label>
                                        <input type="text" id="NameAr" class="form-control" value="@Model.NameAr" disabled />
                                    </div>
                                </div>
                                <!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="NameEn" class="mb-1">اسم اللجنة بالإنجليزي</label>
                                        <input type="text" id="NameEn" class="form-control" value="@Model.NameEn" disabled />
                                    </div>
                                </div>
                                <!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="DescriptionAr" class="mb-1">الوصف بالعربي</label>
                                        <textarea id="DescriptionAr" class="form-control" disabled>@Model.DescriptionAr</textarea>


                                    </div>
                                </div>
                                <!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="DescriptionEn" class="mb-1">الوصف بالإنجليزي</label>
                                        <textarea id="DescriptionEn" class="form-control" disabled>@Model.DescriptionEn</textarea>

                                    </div>
                                </div>
                                <!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="Gender" class="mb-1">الجنس</label>
                                        <input type="text" id="Gender" class="form-control" value="@(Model.Gender == true ? "ذكور" : "إناث")" disabled />
                                    </div>
                                </div>
                                <!-- END ITEM -->

                            </div>

                            <div class="row">
                                <div class="d-flex justify-content-end">
                                    <a asp-action="Index" class="btn btn-secondary">العودة إلى القائمة</a>

                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SHARKNA/Areas/Admin/Views/Boards/Index.cshtml
@model IEnumerable<BoardViewModel>

@{
    ViewData["Title"] = "Board List";
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function confirmCancel(boardId) {
        Swal.fire({
            title: 'تأكيد الحذف؟',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'نعم',
            cancelButtonText: 'لا'
        }).then((result) => {
            if (result.isConfirmed) {
                document.getElementById('cancelForm-' + boardId).submit();
            }
        });
    }
</script>

<script>
    function Display
</script>

<!DOCTYPE html>
<html lang="en" dir="rtl" data-theme="light">
<body>
    <script>

    </script>
    <!-- Start Page Wrap -->
    <section class="page_wrap">
        <div class="page_content">
            <div class="block mb-4">
                <div class="block-header border-bottom px-4 py-3">
                    <h5 class="m-0">إدارة اللجان</h5>
                    <div class="d-flex gap-2">
                        <div class="form-group">
                            <input type="text" class="form-control table__quick_search" placeholder="البحث السريع ...">
                        </div>
                        <div>
                            <a asp-action="Create"  class="btn btn-primary">إضافة لجنة</a>
                        </div>
                    </div>
                </div>
                <div class="block-body">
                    <table class="table table-hover js-dataTable">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.NameAr)</th>
                               @* <th>@Html.DisplayNameFor(m => m.NameEn)</th>
                                <th>@Html.DisplayNameFor(m => m.DescriptionAr)</th>
                                <th>@Html.DisplayNameFor(m => m.DescriptionEn)</th>*@
                                <th>@Html.DisplayNameFor(m => m.Gender)</th>
                                <th>الإجراءات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var board in Model)
                            {
                                <tr>
                                    <td>@board.NameAr</td>
                                  @*  <td>@board.NameEn</td>
                                    <td>@board.DescriptionAr</td>
                                    <td>@board.DescriptionEn</td>*@
                                    <td>
                                        @if (board.Gender.HasValue)
                                        {
                                            @if (board.Gender == true)
                                            {
                                                @:ذكور
                                            }
                                            else
                                            {
                                                @:إناث
                                            }
                                        }
                                        else
                                        {
                                            @:  ذكور وإناث
                                        }
                                    </td>


                                    <td>
                                        <a asp-action="Update" asp-route-id="@board.Id" class="btn btn-success">تعديل</a> |

                                        <form asp-action="Delete" asp-route-id="@board.Id" id="cancelForm-@board.Id" method="post" style="display:inline;">
                                            <button type="button" onclick="confirmCancel('@board.Id')" class="btn btn-danger">حذف</button> |
                                        </form>
                                        <a asp-action="Details" asp-route-id="@board.Id" class="btn btn-primary">عرض التفاصيل</a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section><!-- End Page Wrap -->


</body>
</html>

SHARKNA/Areas/Admin/Views/Boards/Update.cshtml
@model SHARKNA.ViewModels.BoardViewModel
@{
    ViewData["Title"] = "Update Board";
}
<script>
    @{
        if (@ViewData["Successful"] != null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Successful"])';
            Swal.fire(result, '', 'success')
                .then(
                    function () {
                        window.location.href = '@Url.Action("Index", "Boards")';
                    }
                );
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] == null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
        else if (@ViewData["Falied"] != null && ViewData["NoRedirect"] != null)
        {
            <Text>
                                    var result = '@Html.Raw(ViewData["Falied"])';
            Swal.fire(result, '', 'error');
            </Text>
        }
    }
</script>
@* <h2>تعديل اللجنة</h2>
 *@
<section class="page_wrap">
    <div class="page_content">

        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h5 class="m-0">تعديل لجنة @Model.NameAr</h5>
            </div>
            <div class="block-body py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form asp-action="Update" method="post">
                            <div class="row">
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">اسم اللجنة بالعربي</label>
                                        <input asp-for="NameAr" type="text" placeholder="اسم اللجنة " class="form-control">
                                        <span asp-validation-for="NameAr" class="text-danger"></span>

                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1"> اسم اللجنة بالإنجليزي</label>
                                        <input asp-for="NameEn" type="text" placeholder="اسم اللجنة بالإنجليزي"
                                               class="form-control text-start">
                                        <span asp-validation-for="NameEn" class="text-danger"></span>

                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">الوصف بالعربي</label>
                                        <textarea asp-for="DescriptionAr" type="text" class="form-control text-start"> </textarea>
                                        <span asp-validation-for="DescriptionAr" class="text-danger"></span>
                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1"> الوصف بالإنجليزي </label>
                                        <textarea asp-for="DescriptionEn" type="text" class="form-control"></textarea>
                                        <span asp-validation-for="DescriptionEn" class="text-danger"></span>
                                    </div>
                                </div><!-- END ITEM -->
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <div class="mb-4">
                                        <label for="" class="mb-1">الجنس</label>
                                        <div class="form-check">
                                            <input type="radio" asp-for="Gender" class="form-check-input" id="Male" name="Gender" value="true" />
                                            <label class="form-check-label" for="Male"> ذكور </label>
                                        </div>
                                        <div class="form-check">
                                            <input type="radio" asp-for="Gender" class="form-check-input" id="Female" name="Gender" value="false" />
                                            <label class="form-check-label" for="Female"> إناث</label>
                                        </div>
                                        <div class="form-check">
                                            @if (Model.Gender == null)
                                            {
                                                <input type="radio" asp-for="Gender" class="form-check-input" id="Both" name="Gender" value="" checked />

                                            }
                                            else
                                            {
                                                <input type="radio" asp-for="Gender" class="form-check-input" id="Both" name="Gender" value=""  />

                                            }
                                            <label class="form-check-label" for="Both"> ذكور وإناث  </label>
                                        </div>
                                        <span asp-validation-for="Gender" class="text-danger"></span>
                                    </div>
                                </div><!-- END ITEM -->

                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="submit" value="Create" class="btn btn-primary px-5" title="save">حفظ</button>
                            </div>

                        </form>


                    </div>
                </div>
            </div>
        </div>



    </div>
</section><!-- End Page Wrap -->